Algoritmo SVC utilizando a vari치vel alvo (diagn칩stico) com apenas 2 classes: Normal e Patol칩gico. Normal = 0, Patol칩gico = 1

In [52]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [80]:
dados = pd.read_csv('../dados/dados_tratado.csv')

In [81]:
dados.head()

,age,sex,height,weight,qrs_duration,p_r_interval,q_t_interval,t_interval,p_interval,qrs,T,P,QRST,heart_rate,q_wave,r_wave,s_wave,R_wave,S_wave,diagnosis
0,75,0,190,80,91,193,371,174,121,-16,13,64,-2,63,0,52,44,0,0,8
1,56,1,165,64,81,174,401,149,39,25,37,-17,31,53,0,48,0,0,0,6
2,54,0,172,95,138,163,386,185,102,96,34,70,66,75,0,40,80,0,0,10
3,55,0,175,94,100,202,380,179,143,28,11,-5,20,71,0,72,20,0,0,1
4,13,0,169,51,100,167,321,174,91,107,66,52,88,84,0,36,48,0,0,14

In [82]:
dados.diagnosis = dados.diagnosis.map(lambda x: 0 if x == 1 else 1)

In [83]:
dados.head()

,age,sex,height,weight,qrs_duration,p_r_interval,q_t_interval,t_interval,p_interval,qrs,T,P,QRST,heart_rate,q_wave,r_wave,s_wave,R_wave,S_wave,diagnosis
0,75,0,190,80,91,193,371,174,121,-16,13,64,-2,63,0,52,44,0,0,1
1,56,1,165,64,81,174,401,149,39,25,37,-17,31,53,0,48,0,0,0,1
2,54,0,172,95,138,163,386,185,102,96,34,70,66,75,0,40,80,0,0,1
3,55,0,175,94,100,202,380,179,143,28,11,-5,20,71,0,72,20,0,0,0
4,13,0,169,51,100,167,321,174,91,107,66,52,88,84,0,36,48,0,0,1

In [84]:
x = dados[['age', 'sex', 'height', 'weight', 'qrs_duration', 'p_r_interval', 'q_t_interval', 't_interval', 'p_interval',
          'qrs', 'T', 'P', 'QRST', 'heart_rate', 'q_wave', 'r_wave', 's_wave', 'R_wave', 'S_wave']]
y = dados['diagnosis']

In [88]:
SEED = 6
np.random.seed(SEED)
raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x, y, test_size= 0.25, stratify=y)

In [89]:
raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x, y, test_size= 0.25, stratify=y)
scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

In [90]:
modelo = SVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)
acuracia = accuracy_score(teste_y, previsoes)
print(f'Acur치cia Modelo:{acuracia* 100} %')

Acur치cia Modelo:76.19047619047619 %

In [63]:
from sklearn.dummy import DummyClassifier
dummy = DummyClassifier()
dummy.fit(treino_x, treino_y)
previsoes = dummy.predict(teste_x)
acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acur치cia do dummy %.2f%%" % acuracia)

A acur치cia do dummy 56.19%

O modelo final teve acur치cia de 76.19 %