In [2]:
import pandas as pd
import numpy as np

In [3]:
dados = pd.read_csv('../dados/dados_tratado.csv')

In [6]:
dados.diagnosis = dados.diagnosis.map(lambda x: 0 if x == 1 else 1)

In [7]:
dados.head()

,age,sex,height,weight,qrs_duration,p_r_interval,q_t_interval,t_interval,p_interval,qrs,T,P,QRST,heart_rate,q_wave,r_wave,s_wave,R_wave,S_wave,diagnosis
0,75,0,190,80,91,193,371,174,121,-16,13,64,-2,63,0,52,44,0,0,1
1,56,1,165,64,81,174,401,149,39,25,37,-17,31,53,0,48,0,0,0,1
2,54,0,172,95,138,163,386,185,102,96,34,70,66,75,0,40,80,0,0,1
3,55,0,175,94,100,202,380,179,143,28,11,-5,20,71,0,72,20,0,0,0
4,13,0,169,51,100,167,321,174,91,107,66,52,88,84,0,36,48,0,0,1

In [8]:
x = dados[['age', 'sex', 'weight', 'height', 'qrs_duration', 'p_r_interval', 'q_t_interval', 't_interval', 'p_interval',
          'qrs', 'T', 'P', 'QRST', 'heart_rate', 'q_wave', 'r_wave', 's_wave', 'R_wave', 'S_wave']]
y = dados['diagnosis']

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

In [10]:
raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x, y, test_size= 0.25, stratify=y)
scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

In [21]:
SEED = 5
np.random.seed(SEED)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

trees = RandomForestClassifier(random_state = SEED, n_estimators=1500, n_jobs=-1)
trees.fit(treino_x, treino_y)
previsoes = trees.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 315 elementos e testaremos com 105 elementos
A acurácia foi 76.19%